package le_ploogin

ActorVtbl :: struct {
    using _mobj : MobileObjectVtbl,
}
//#assert(size_of(MobileObjectVtbl) == 0x300)

ActorData :: struct {
    pkRagdollController     : ^bhkRagdollController,
    pkPenetrationDetection  : ^bhkRagdollPenetrationUtil,
    ePersuasionEmotion      : u32,
    fEmotionValue           : f32,
    bProcessMe              : bool,
    pkMyKiller              : ^Actor,
    bMurderAlarm            : bool,
    fCheckMyDeadBodyTimer   : f32,
    fDeadBodyAlarm          : f32,
    kPermanentModifiers     : ModifierList,
    kBaseValueOverrides     : ModifierList,
    bBlockPostAnim          : bool,
    bReloadTargetQueued     : bool,
    bRunsInLow2             : bool,
    kCastPowers             : BSSimpleList(^CastPowerItem),
    kDispModifierList       : BSSimpleList(^DispositionModifier),
    bInCombat               : bool,
    eLifeState              : u32,
    eCriticalStage          : u32,
    eQueuedAttack           : u32,
    fLastUpdate             : f32,
    bDeadFlag               : bool,
    iVisFlags               : u32,
    iLastSeenTime           : u32,
    bForceRun               : bool,
    bForceSneak             : bool,
    bForceUpdateQuestTarget : bool,
    bSearchingInCombat      : bool,
    pkCurrentCombatTarget   : ^Actor,
    pkCurrentCombatTargetArray : rawptr,
    pkCurrentCombatMemberArray : rawptr,
    bAttackOnNextTheft      : bool,
    iThiefCrimeStamp        : u32,
    iMinorCrimes            : u32,
    iMajorCrimes            : u32,
    bIgnoreCrime            : bool,
    bEVPBuffered            : bool,
    bResetAI                : bool,
    pkTemplateActorBase     : ^TESActorBase,
    bInWater                : bool,
    bSwimming               : bool,
    bUpdateLighting         : bool,
    iActionValue            : u32,
    fTimerOnAction          : f32,
    fHeadTrackTimer         : f32,
    bWasInFrustum           : bool,
    bShouldRotateToTrack    : bool,
    fEditorLocCoord         : [3]f32,
    fEditorLocZRot          : f32,
    pkEditorLocForm         : ^TESForm,
    bSetOnDeath             : bool,
    bContainerReset         : bool,
    fGunSkillGun            : f32,
    fGunSkillHUD            : f32,
    fGunSkillActor          : f32,
    fGunSkillVATS           : f32,
    fCurrentWeaponCondition : f32,
    bFootIKInRange          : bool,
    bPlayerTeammate         : bool,
    bLightingUpdatedNonMoving : bool,
    pkActorMover            : ^ActorMover,
    pkLastHitData           : ^HitData,
    pkInitialPackage        : ^TESPackage,
    fRadiationResistanceMult : f32,
    pkContinuousBeamPersistant : ^ContinuousBeamProjectile,
    iEmotion                : u32,
    iEmotionValue           : u32,
    iCurrentSitSleepState   : u32,
    bTurretBehavior         : bool,
    bForceHitReaction       : bool,
}
#assert(size_of(ActorData) == 0x108)

Actor :: struct {
    using _vtbl_actr         : ^ActorVtbl,
    using _data_form         : TESFormData,

    using _vtbl_childcell    : ^TESChildCELLVtbl,
    using _data_childcell    : TESChildCELLData,

    using _data_refr         : TESObjectREFRData,
    using _data_mobj         : MobileObjectData,

    using _vtbl_mgcs         : ^MagicCasterVtbl,
    using _data_mgcs         : MagicCasterData,
    using _vtbl_mgtg         : ^MagicTargetVtbl,
    using _data_mgtg         : MagicTargetData,
    using _vtbl_avow         : ^ActorValueOwnerVtbl,
    using _data_avow         : ActorValueOwnerData,
    using _vtbl_cvow         : ^CachedValuesOwnerVtbl,
    using _data_cvow         : CachedValuesOwnerData,

    using _data_actr         : ActorData,
}
#assert(size_of(Actor) == 0x1B4)