package le_ploogin

PlayerCharacterVtbl :: struct {
    using _char : ActorVtbl,
}
//#assert(size_of(CharacterVtbl) == 0x300)

PlayerCharacterData :: struct {
    kPlayerAchievements             : [3]AchievementInstance,
    pkQueuedTargetLoc               : ^PlayerTargetLoc,
    pkQueuedWeaponAttach            : ^TESObjectWEAP,
    fTimeSinceLastAmmoRegenTick     : f32,
    cShotsSinceLastAmmoRegen        : u8,
    iSandmanDetection               : u32,
    iCombatPersue                   : u32,
    bTravelUseDoor                  : bool,
    bOnElevator                     : bool,
    bForceQuestTargetUpdate         : bool,
    pClosestConversation            : ^DialoguePackage,
    bTransporting                   : bool,
    pkActiveEffectList              : ^BSSimpleList(^ActiveEffect),
    pkCurrentSpell                  : ^MagicItem,
    pkDesiredTarget                 : ^MagicTarget,
    pkCameraCaster                  : ^CameraCaster,
    pkHitCaster                     : ^HitCaster,
    pkAIConversationRunning         : ^DialoguePackage,
    iNumberOfStealWarnings          : u32,
    fStealWarningTimer              : f32,
    iNumberOfPickpocketWarnings     : u32,
    fPickPocketWarningTimer         : f32,
    pkEatDrinkItems                 : ^BSSimpleList(^MagicItem),
    pkQueuedWornEnchantments        : ^BSSimpleList(^TESBoundObject),
    bShowQuestItemsInInventory      : bool,
    fTemporaryActorValueModifiers   : [77]f32,
    fScriptActorValueModifiers      : [77]f32,
    fHealthModifier                 : f32,
    fDamageActorValueModifiers      : [77]f32,
    kListNotes                      : BSSimpleList(^BGSNote),
    pkIronsightsDOFInstance         : ^ImageSpaceModifierInstanceDOF,
    pkVATSDOFInstance               : ^ImageSpaceModifierInstanceDOF,
    pkVATSDRBInstance               : ^ImageSpaceModifierInstanceDRB,
    bHostileDetection               : bool,
    bIsAcousticSpaceTransition      : bool,
    kListOfTeammates                : BSSimpleList(^Actor),
    pkLastExtDoorActivated          : ^TESObjectREFR,
    bSpeaking                       : bool,
    pkListOfActions                 : ^BSSimpleList(^PlayerActionObject),
    pkListOfCasinoData              : ^BSSimpleList(^CasinoData),
    pkInactiveListOfCaravanCards    : ^BSSimpleList(^TESCaravanCard),
    pkActiveListOfCaravanCards      : ^BSSimpleList(^TESCaravanCard),
    iCaravanCapWinnings             : u32,
    iCaravanCapLosses               : u32,
    iCaravanWinnings                : u32,
    iCaravanLosses                  : u32,
    iCaravanLargestWinning          : u32,
    iCasinoCheatLevel               : u32,
    spkGrabSpring                   : ^bhkMouseSpringAction,
    pkGrabbedObject                 : ^TESObjectREFR,
    eGrabType                       : u32,
    fGrabObjectWeight               : f32,
    fGrabDistance                   : f32,
    bSave3rdPerson                  : bool,
    b3rdPersonSaved                 : bool,
    b3rdPerson                      : bool,
    bActually3rdPerson              : bool,
    bWant3rdPerson                  : bool,
    bTemp3rdPerson                  : bool,
    bTemp3rdPersonSwitchBack        : bool,
    bTemp1stPerson                  : bool,
    bTemp1stPersonSwitchBack        : bool,
    bAlwaysRun                      : bool,
    bAutoMove                       : bool,
    iSleepTime                      : u32,
    bIsSleeping                     : bool,
    fFOV                            : f32,
    fSecondRunning                  : f32,
    fSecondSwimming                 : f32,
    fSecondSneaking                 : f32,
    bActorInSneakRange              : bool,
    bCanFastTravel                  : bool,
    bCanWait                        : bool,
    fWorldFOV                       : f32,
    f1stPersonFOV                   : f32,
    f3rdPersonFOV                   : f32,
    iNumberTraining                 : u32,
    ucControlsDisabled              : u8,
    bBlockActivate                  : bool,
    fBlockActivateTimer             : f32,
    pkForceActivateRef              : ^TESObjectREFR,
    pk1stPersonBipedAnim            : ^BipedAnim,
    pk1stPersonAnimation            : ^Animation,
    sp1stPerson3D                   : ^NiAVObject,
    fEyeHeight                      : f32,
    spInventoryPC                   : ^NiNode,
    pkInventoryAnimation            : ^Animation,
    pkInventoryWeaponEffect         : ^MagicShaderHitEffect,
    kListTopics                     : BSSimpleList(^TESTopic),
    kListQuestLog                   : BSSimpleList(^TESQuestStageItem),
    pkActiveQuest                   : ^TESQuest,
    kListObjectives                 : BSSimpleList(^BGSQuestObjective),
    kListQuestTargets               : BSSimpleList(^TESQuestTarget),
    bGreetingPlayer                 : bool,
    fGreetTimer                     : f32,
    iHoursToSleep                   : i32,
    cMurder                         : u8,
    iAmountStolenGold               : u32,
    fSortActorDistanceTimer         : f32,
    fSitHeadingDelta                : f32,
    bBeenAttacked                   : bool,
    pkSelectedSpell                 : ^MagicItem,
    pkSelectedScroll                : ^TESObjectBOOK,
    pkPlayerMapMarker               : ^TESObjectREFR,
    kPlayerMarkerPath               : TeleportPath,
    fProjectileReleaseTimer         : f32,
    iNumAdvance                     : i32,
    eSkillAdvance                   : i32,
    pkClassDefault                  : ^TESClass,
    pkClassBasedOn                  : ^TESClass,
    iCrimeCount                     : [5]u32,
    pkPendingPoison                 : ^AlchemyItem,
    bChargen                        : bool,
    bAllowEGMCacheClear             : bool,
    bTelekinesisIsSelected          : bool,
    pkOccupiedRegion                : ^TESRegion,
    kAllOccupiedRegions             : TESRegionList,
    kCurrentRegionSoundList         : BSSimpleList(^TESRegionSound),
    kStatusSoundHandle              : BSSoundHandle,
    pkInitialStateBuffer            : rawptr,
    iLastPlayingTimeUpdate          : u32,
    iTotalPlayingTime               : u32,
    iCharacterSeed                  : u32,
    bAIControlledToPos              : bool,
    bAIControlledFromPos            : bool,
    bAIControlledActivate           : bool,
    bAIControlledPackage            : bool,
    bInBorderContainedCell          : bool,
    bReturnToLastKnownGoodPosition  : bool,
    fLastKnownGoodPosition          : [3]f32,
    pkLastKnownGoodLocation         : ^TESForm,
    pkBorderRegions                 : ^NiTPrimitiveArray(^TESRegion),
    pkLastKnownMusicType            : ^BGSMusicType,
    eDifficultyLevel                : u32,
    eHardcoreSetting                : u32,
    eKillCameraSetting              : u32,
    bBeingChased                    : bool,
    bIsYoung                        : bool,
    bIsToddler                      : bool,
    bCanUsePowerArmor               : bool,
    kMapMarkerList                  : BSSimpleList(^MapMarker),
    pkMapWorld                      : ^TESWorldSpace,
    kAudioMarkerList                : BSSimpleList(^AudioMarkerInfo),
    pkClosestAudioMarkerInfo        : ^AudioMarkerInfo,
    fUFOCameraHeading               : f32,
    fUFOCameraPitch                 : f32,
    UFOCameraPos                    : [3]f32,
    iSelectedSpellCastSoundID       : u32,
    kSelectedSpellCastSound         : BSSoundHandle,
    kMagicFailureSounds             : [6]BSSoundHandle,
    kDroppedRefList                 : BSSimpleList(^TESObjectREFR),
    kRandomDoorSpaceMap             : NiTMap(u32, u8),
    sp1stPersonLight                : ^NiLight,
    sp3rdPersonLight                : ^NiLight,
    bInsufficientChargeMessageShown : bool,
    fDropAngleMod                   : f32,
    fLastDropAngleMod               : f32,
    pkCharacterProgressionInfo      : CharacterProgressionData,
    kPerks                          : BSSimpleList(^PerkRankData),
    kPerkEntryLists                 : [74]BSSimpleList(^BGSPerkEntry),
    kCompanionPerks                 : BSSimpleList(^PerkRankData),
    kCompanionPerkEntryLists        : [74]BSSimpleList(^BGSPerkEntry),
    pkAutoAimActor                  : ^Actor,
    fBulletAutoAim                  : [3]f32,
    spTargeted3D                    : ^NiAVObject,
    bTarget3DDistant                : bool,
    pkPlayersTargetActor            : ^Actor,
    pkListOfPerceivedActor          : ^BSSimpleList(^ActorsNearPlayerData),
    fMenuModeButtonTimer            : f32,
    fAmmoSwapButtonTimer            : f32,
    bMenuModeButtonClicked          : bool,
    fCamera3rdPersonShoulderOffset  : [3]f32,
    pkCombatGroup                   : ^CombatGroup,
    iTeammateCount                  : u32,
    fCombatTimer                    : f32,
    fYieldTimer                     : f32,
    pkWobbleNodes                   : [2][12]^NiAVObject,
    fCatched1stPersonCameraPos      : [3]f32,
    fCachedWorldCameraPos           : [3]f32,
    spCameraRigidBody               : ^bhkRigidBody,
    bPlayerInCombat                 : bool,
    bAllCombatTargetSearching       : bool,
    bMegatonDestroyed               : bool,
    kRockItLauncherAmmoList         : BSSimpleArray(^ItemChange, 1024),
    bNightVisionOn                  : bool,
    pkReputationUpdate              : ^TESReputation,
    cSloMoCameraHits                : u8,
    fTimeSinceLastAttack            : f32,
    fTimeInSlowMoCam                : f32,
    fKillCamCooldown                : f32,
    bIgnoreGTM                      : bool,
    bTurboISM                       : bool,
    fLastHelloTime                  : f32,
    fCounterAttackTimer             : f32,
    bCounterAttackCamera            : bool,
    bHasCateyeActive                : bool,
    bHasSpotterActive               : bool,
    fCheckForItems                  : f32,
    pkWeaponSightingNode            : ^NiAVObject,
    bAlwaysHardcore                 : bool,
    bResetHardcoreTimers            : bool,
    kHotkeyLastAmmo                 : BSSimpleArray(^TESAmmo, 1024),
}
//#assert(size_of(CharacterData) == 0x108)

PlayerCharacter :: struct {
    using _vtbl_actr         : ^PlayerCharacterVtbl,
    using _data_form         : TESFormData,

    using _vtbl_childcell    : ^TESChildCELLVtbl,
    using _data_childcell    : TESChildCELLData,

    using _data_refr         : TESObjectREFRData,
    using _data_mobj         : MobileObjectData,

    using _vtbl_mgcs         : ^MagicCasterVtbl,
    using _data_mgcs         : MagicCasterData,
    using _vtbl_mgtg         : ^MagicTargetVtbl,
    using _data_mgtg         : MagicTargetData,
    using _vtbl_avow         : ^ActorValueOwnerVtbl,
    using _data_avow         : ActorValueOwnerData,
    using _vtbl_cvow         : ^CachedValuesOwnerVtbl,
    using _data_cvow         : CachedValuesOwnerData,

    using _data_actr         : ActorData,
    using _data_char         : CharacterData,
    using _data_plch         : PlayerCharacterData,
}
#assert(size_of(PlayerCharacter) == 0xE50)

GetPlayerCharacter :: proc "c" () -> ^PlayerCharacter {
    return (cast(^^PlayerCharacter)cast(uintptr)0x011DEA3C)^
}